name: Manual Trigger for Shell Test on CircleCI

on:
  issue_comment:
    types: [created, edited]  # PR에 새로운 커맨트가 생성될 때 트리거

jobs:
  comment-run:
    if: |
      github.event.comment.body == '/run shell' &&
      startsWith(github.event.issue.pull_request.url, 'https://api.github.com/repos/tw-kang/cubrid/pulls/')
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI Shell Test
        env:
          CIRCLECI_TOKEN: ${{ secrets.CIRCLECI_TOKEN }}
        run: echo "/run test"
