name: Manual Trigger

on:
  issue_comment:
    types: [created, edited]

jobs:
  run_shell:
    name: run shell test on circleci
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
        env:
          CIRCLECI_TOKEN: ${{ secrets.CIRCLECI_TOKEN }}
        run: | 
          echo "/run test"
